name: Check Markdown links
on: 
  schedule:
    - cron: '* */24 * * *'
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.7
        with:
          folder-path: "docs"
